plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  instance-state-name: running
  tag:Environment: Challenge

keyed_groups:
  - key: tags.Tier
    prefix: tier
    separator: "_"

hostnames:
  - private-ip-address

compose:
  ansible_user: "'ubuntu'"