name: teemii

services:
  backend:
    image: dokkaner/teemii-backend:latest
    container_name: teemii-backend
    restart: unless-stopped

    environment:
      EXPRESS_PORT: "3000"
      SOCKET_IO_PORT: "1555"

    expose:
      - "3000"
      - "1555"

    volumes:
      - teemii-data:/data

    networks:
      - teemii-network

  frontend:
    image: dokkaner/teemii-frontend:latest
    container_name: teemii-frontend
    restart: unless-stopped

    depends_on:
      - backend

    environment:
      VITE_APP_TITLE: "Teemii"
      VITE_APP_PORT: "80"

    ports:
      - "8080:80"

    networks:
      - teemii-network

networks:
  teemii-network:
    name: teemii-network
    driver: bridge

volumes:
  teemii-data:
    name: teemii-data