#Trabaja con un solo proceso
worker_processes 4;

events {
    worker_connections 1024;
}

http {
    #Solicitudes recibidas
    access_log /var/log/nginx/access.log;

    #Errores de nginx
    error_log /var/log/nginx/error.log;

    server {
        listen 80;

        location / {
            return 200 "Servidor Nginx funcionando con configuracion limitada\n";
        }

        location /stub_status {
            stub_status;
            allow all;
        }
    }
}